# Setup
title: Ukja2
description: Practice & Practice 
url: https://ukja2.github.io
avatar: /MeMe.jpg
permalink: /:categories/:title/
cover_image: /bg.jpg

# Timezone settings
timezone: Asia/Seoul

# Excerpt settings
excerpt_separator: <!--more-->

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.mdpost.excerpt 
  - not-pure-poole.gemspec
  - node_modules
  - package-lock.json

# Optimize Jekyl SEO Tag
#twitter:
#  username: vszhub
  #card: summary
#logo: logo.png
#social:
  #name: Songzi Vong
  #links:
    #- https://twitter.com/vszhub
    #- https://github.com/vszhub
#google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Ukja2
  url: https://ukja2.github.io
  email: jaewooklee739@gmail.com

# Tags settings
tag_page: /tags/

# 다른 지킬 테마와 달리 아래 설정을 추가해주어야 깃허브 로그인이 정상적으로 작동함
utterances:
  repo: "Ukja2/ukja2.github.io"
  issue-term: "pathname"
  theme: "github-light"

# Build settings
markdown: kramdown
include: ["_pages"]

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Site settings
last_modified_at: "%Y-%m-%d %H:%M:%S %z"